services:
  - type: web
    name: bot-messenger-ia
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PAGE_ACCESS_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
